#!/bin/sh

# Cleanup previous simulation artifacts
echo "Cleaning up previous simulation files..."
rm -rf obj_dir
rm -f counter.vcd bin2bcd.vcd top.vcd

# Run Verilator to translate SystemVerilog into C++, including the C++ testbench
echo "Running Verilator..."
verilator -Wall --cc --trace top.sv counter.sv bin2bcd.sv --exe top_tb.cpp

# Attach Vbuddy
echo "Attaching USB devices..."
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# Build C++ project via make automatically generated by Verilator
echo "Building C++ project..."
make -j -C obj_dir/ -f Vtop.mk Vtop

# Run executable simulation file
echo "Running the simulation..."
obj_dir/Vtop